In [1]:
import numpy as np

In [2]:
# 2. Примеры создания массивов

# 2.1. Массив из обычного списка
list_data = [1, 2, 3, 4, 5]
arr_from_list = np.array(list_data)
print("Массив из списка:", arr_from_list)

# 2.2. Массивы с использованием zeros, ones, arange

# массив из нулей
zeros_arr = np.zeros((2, 3))   # 2 строки, 3 столбца
print("\nМассив из нулей:\n", zeros_arr)

# массив из единиц
ones_arr = np.ones(5)          # одномерный массив из 5 элементов
print("\nМассив из единиц:", ones_arr)

# массив с последовательностью чисел
arange_arr = np.arange(0, 10, 2)  # от 0 до 10 с шагом 2
print("\nМассив с arange:", arange_arr)

Массив из списка: [1 2 3 4 5]

Массив из нулей:
 [[0. 0. 0.]
 [0. 0. 0.]]

Массив из единиц: [1. 1. 1. 1. 1.]

Массив с arange: [0 2 4 6 8]


In [3]:
# 3. Демонстрация атрибутов shape и dtype

print("Массив arr_from_list:", arr_from_list)
print("Форма (shape):", arr_from_list.shape)   # размерность массива
print("Тип данных (dtype):", arr_from_list.dtype)  # тип элементов

Массив arr_from_list: [1 2 3 4 5]
Форма (shape): (5,)
Тип данных (dtype): int64


In [4]:
# 4. Примеры индексирования и срезов

# Возьмём двумерный массив для наглядности
matrix = np.arange(1, 13).reshape(3, 4)  # 3 строки, 4 столбца
print("Матрица:\n", matrix)

# 4.1. Получение отдельного элемента (например, элемент из 2-й строки и 3-го столбца)
elem = matrix[1, 2]   # индексация с нуля
print("\nОтдельный элемент (2-я строка, 3-й столбец):", elem)

# 4.2. Извлечение подмассива с помощью среза
# возьмём первые две строки и последние два столбца
submatrix = matrix[0:2, 2:4]
print("\nПодмассив (первые две строки, последние два столбца):\n", submatrix)


Матрица:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Отдельный элемент (2-я строка, 3-й столбец): 7

Подмассив (первые две строки, последние два столбца):
 [[3 4]
 [7 8]]


In [5]:
# 5. Примеры векторных операций и базовых статистик

# Создадим два массива одинаковой длины
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("a:", a)
print("b:", b)

# 5.1. Поэлементное сложение массивов
sum_arr = a + b               # то же самое, что np.add(a, b)
print("\nПоэлементное сложение a + b:", sum_arr)

# 5.2. Поэлементное умножение массивов
mul_arr = a * b               # то же самое, что np.multiply(a, b)
print("Поэлементное умножение a * b:", mul_arr)

# 5.3. Вычисление средней величины (mean) и других простых статистик
mean_value = a.mean()
max_value = a.max()
min_value = a.min()

print("\nСреднее значение массива a:", mean_value)
print("Максимум в массиве a:", max_value)
print("Минимум в массиве a:", min_value)

a: [1 2 3 4]
b: [10 20 30 40]

Поэлементное сложение a + b: [11 22 33 44]
Поэлементное умножение a * b: [ 10  40  90 160]

Среднее значение массива a: 2.5
Максимум в массиве a: 4
Минимум в массиве a: 1
